# Generated by Django 5.0.7 on 2026-02-03 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_recurringtransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envelope',
            options={'ordering': ['category__name']},
        ),
        migrations.AlterField(
            model_name='envelope',
            name='budgeted_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.category'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
